import { mkdir, readFile, rename, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(__dirname, '..');

const DEFAULT_SCORES_FILE = path.join(projectRoot, 'data', 'top-scores.yml');
const MAX_PLAYER_NAME_LENGTH = 14;
const MAX_SCORE_ENTRIES = 100;
const REQUEST_SIZE_LIMIT = 16 * 1024;
let writeQueue = Promise.resolve();

const scoreFilePath = () => path.resolve(process.env.SCORES_FILE || DEFAULT_SCORES_FILE);

const sanitizePlayerName = (name) => {
  const trimmed = String(name ?? '').trim().replace(/\s+/g, ' ');
  return trimmed.slice(0, MAX_PLAYER_NAME_LENGTH);
};

const safeFiniteNumber = (value, fallback = 0) => {
  const number = Number(value);
  return Number.isFinite(number) ? number : fallback;
};

const rankScores = (entries, limit = MAX_SCORE_ENTRIES) =>
  entries
    .map((entry) => ({
      id: String(entry.id ?? ''),
      name: sanitizePlayerName(entry.name),
      points: Math.max(0, Math.round(safeFiniteNumber(entry.points, 0))),
      durationSeconds: Math.max(0, safeFiniteNumber(entry.durationSeconds, 0)),
      completedAt: String(entry.completedAt ?? ''),
    }))
    .filter((entry) => entry.id && entry.name && entry.completedAt)
    .sort((left, right) => right.points - left.points || left.durationSeconds - right.durationSeconds || right.completedAt.localeCompare(left.completedAt))
    .slice(0, limit);

const parseYamlScalar = (value) => {
  const trimmed = value.trim();
  if (trimmed.startsWith('"') && trimmed.endsWith('"')) {
    try {
      return JSON.parse(trimmed);
    } catch {
      return trimmed.slice(1, -1);
    }
  }

  const number = Number(trimmed);
  return Number.isFinite(number) ? number : trimmed;
};

const parseYamlField = (text, entry) => {
  const match = /^([A-Za-z][A-Za-z0-9]*):\s*(.*)$/.exec(text.trim());
  if (!match) return;
  entry[match[1]] = parseYamlScalar(match[2]);
};

const parseScoresYaml = (yaml) => {
  const entries = [];
  let currentEntry = null;

  for (const line of yaml.split(/\r?\n/)) {
    if (line.startsWith('  - ')) {
      if (currentEntry) entries.push(currentEntry);
      currentEntry = {};
      parseYamlField(line.slice(4), currentEntry);
      continue;
    }

    if (currentEntry && line.startsWith('    ')) {
      parseYamlField(line.slice(4), currentEntry);
    }
  }

  if (currentEntry) entries.push(currentEntry);
  return rankScores(entries);
};

const yamlScalar = (value) => {
  if (typeof value === 'number') return String(value);
  return JSON.stringify(String(value ?? ''));
};

const serializeScoresYaml = (entries) => {
  const rows = rankScores(entries)
    .map(
      (entry) =>
        `  - id: ${yamlScalar(entry.id)}\n` +
        `    name: ${yamlScalar(entry.name)}\n` +
        `    points: ${yamlScalar(entry.points)}\n` +
        `    durationSeconds: ${yamlScalar(entry.durationSeconds)}\n` +
        `    completedAt: ${yamlScalar(entry.completedAt)}`,
    )
    .join('\n');

  return `# Monkey Madness shared top scores\n# Generated by server/scores.mjs.\nscores:\n${rows ? `${rows}\n` : ''}`;
};

export const readScores = async () => {
  try {
    return parseScoresYaml(await readFile(scoreFilePath(), 'utf8'));
  } catch (error) {
    if (error?.code === 'ENOENT') return [];
    throw error;
  }
};

export const saveScores = async (entries) => {
  const rankedEntries = rankScores(entries);
  const targetPath = scoreFilePath();
  const tempPath = `${targetPath}.${process.pid}.${Date.now()}.tmp`;

  await mkdir(path.dirname(targetPath), { recursive: true });
  await writeFile(tempPath, serializeScoresYaml(rankedEntries), 'utf8');
  await rename(tempPath, targetPath);

  return rankedEntries;
};

export const addScore = async ({ name, points, durationSeconds }) => {
  const cleanName = sanitizePlayerName(name);
  if (!cleanName) {
    const error = new Error('Name is required.');
    error.statusCode = 400;
    throw error;
  }

  const entry = {
    id: `${Date.now()}-${Math.random().toString(36).slice(2)}`,
    name: cleanName,
    points: Math.max(0, Math.round(safeFiniteNumber(points, 0))),
    durationSeconds: Math.max(0, safeFiniteNumber(durationSeconds, 0)),
    completedAt: new Date().toISOString(),
  };

  const result = writeQueue.then(async () => {
    const scores = await saveScores([...(await readScores()), entry]);
    return { entry, scores };
  });

  writeQueue = result.catch(() => {});
  return result;
};

const readRequestJson = async (request) =>
  new Promise((resolve, reject) => {
    let body = '';
    let tooLarge = false;

    request.setEncoding('utf8');
    request.on('data', (chunk) => {
      if (tooLarge) return;
      body += chunk;
      if (body.length > REQUEST_SIZE_LIMIT) {
        tooLarge = true;
        const error = new Error('Request body is too large.');
        error.statusCode = 413;
        reject(error);
      }
    });
    request.on('end', () => {
      if (tooLarge) return;
      try {
        resolve(body ? JSON.parse(body) : {});
      } catch {
        const error = new Error('Request body must be valid JSON.');
        error.statusCode = 400;
        reject(error);
      }
    });
    request.on('error', reject);
  });

const sendJson = (response, statusCode, payload) => {
  response.statusCode = statusCode;
  response.setHeader('content-type', 'application/json; charset=utf-8');
  response.setHeader('cache-control', 'no-store');
  response.end(JSON.stringify(payload));
};

export const handleScoresApi = async (request, response) => {
  const url = new URL(request.originalUrl || request.url || '/', 'http://localhost');
  if (url.pathname !== '/api/scores') return false;

  try {
    if (request.method === 'GET') {
      sendJson(response, 200, { scores: await readScores() });
      return true;
    }

    if (request.method === 'POST') {
      const result = await addScore(await readRequestJson(request));
      sendJson(response, 201, result);
      return true;
    }

    response.setHeader('allow', 'GET, POST');
    sendJson(response, 405, { error: 'Method not allowed.' });
    return true;
  } catch (error) {
    sendJson(response, error.statusCode || 500, {
      error: error.statusCode ? error.message : 'Score storage failed.',
    });
    return true;
  }
};
